### ISSUE TITLE
Question: Callback URL Defaults

### ISSUE THREAD

**Issue by amiller-gh** [Bandwidth/node-voice#25]
Hi all!

We're finally integrating voice into our application. In the dashboard, we're able to set our "Call initiated callback method" and "Call status callback method" for each voice application we create. These are also available in the admin API when creating apps programmatically.

However, when creating a new call, the API appears to error if we don't *also* provide these URLs to your API server!

```
Expected type: ‘Optional<Object<{from,to,callTimeout,callbackTimeout,answerUrl,answerFallbackUrl,username,password,fallbackUsername,fallbackPassword,answerMethod,answerFallbackMethod,disconnectUrl,disconnectMethod,tag,applicationId,obfuscatedTo,obfuscatedFrom}>>’
    at DefaultRequestBuilder.prepareArgs (/Users/ruthwu/Universe/app/node_modules/@bandwidth/voice/dist/voice.cjs.development.js:770:11)
    at ApiController.createCall (/Users/ruthwu/Universe/app/node_modules/@bandwidth/voice/dist/voice.cjs.development.js:1860:24)
    at POST (/Users/ruthwu/Universe/app/packages/@universe/api/dist/src/api/v1/calling/providers/bandwidth/call.js:219:50)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errors: { body: [ [Object] ] }
}
```

Is this intended behavior? My hope would be the application can provide default webhook URLs, and you can either rely on default endpoints in the app (and not send them in every voice API call) or choose to override them per call if we do provide a value.

**Comment by ajrice6713** [comment]
Hey @amiller-gh! 

Are you referring to providing the callback URL in the createCall function? 

If so, then this is intended behavior and we do require that you provide the callback URL when creating the call object - the callback URL that you set up in the dashboard is intended for inbound traffic - and when we send a webhook there to initiate an inbound call to one of your tns, we send an [initiate event](https://dev.bandwidth.com/voice/bxml/callbacks/initiate.html). 

The callback URL you provide in the createCall function is intended as an answer URL, and when the outbound call is answered, we send an [answer event](https://dev.bandwidth.com/voice/bxml/callbacks/answer.html).

The purpose of the behavior is to allow for users with different inbound and outbound use cases to keep the logic separated at two different services as opposed to using one and having to pass some conditional before deciding how to handle the call flow. 

A change in this behavior would be at the API layer and not the SDK layer - and so I would be happy to put in a feature request to have us default to the callback URL in the application ID provided in the request body if no answer URL is provided - if we are on the same page here.

Let me know if I am missing anything/offbase and we can work through this!

**Comment by amiller-gh** [comment]
Nope! Just different from the Messaging APIs, so the clarification is helpful. An additional sentence or two in the documentation to this effect may be helpful.
