### ISSUE TITLE
[BUG] Calling getDownloadCallRecording tries to parse the response body as if it was JSON

### ISSUE THREAD

**Issue by bernardodesousa** [Bandwidth/node-voice#43]
### Checklist
 - [x] Have you provided a description of the bug?
 - [x] Have you provided your Environment information?
 - [x] Have you provided a sample code snippet?
 - [x] Have you provided a stack trace?
 - [x] Have you outlined the expected behavior?

### Description

Calling getDownloadCallRecording tries to parse the response body as if it was JSON, resulting in the following error:

`Error: Could not parse body as JSON.`
`Unexpected token R in JSON at position 0`

The response contains RIFF/WAVE data, not JSON. I was able to build my own request using [got](https://github.com/sindresorhus/got) and the response contains a body that starts with "RIFF [some non printable characters] WAVE". That's why the JSON parser complains about the R. It's the beginning of a wave file header, not JSON. Also, the response header "content-type" is "audio/vnd.wave".

### Environment Information

 - OS Version: Ubuntu 18.04 on WSL 2, on Windows 10.
 - SDK Version: 4.1.1
 - Environment: NodeJS v14.19.0

### Sample Code Snippet

The code is precisely the example provided in the documentation. I just added the input values (credentials, accountId, callId, and recordingId).

```js
import { Client, ApiController } from '@bandwidth/voice'

const BW_USERNAME = "****";
const BW_PASSWORD = "****"
const BW_ACCOUNT_ID = "****";
const client = new Client({
    basicAuthUserName: BW_USERNAME,
    basicAuthPassword: BW_PASSWORD
})

const controller = new ApiController(client);
const accountId = BW_ACCOUNT_ID
const callId = '****';
const recordingId = '****';

try {
    const response = await controller.getDownloadCallRecording(accountId, callId, recordingId);
    console.log(response);
} catch (error) {
    console.error(error)
}
```

### Stack Trace

```shell
Error: Could not parse body as JSON.

Unexpected token R in JSON at position 0
    at DefaultRequestBuilder.callAsJson (/home/posu/n2uitive/bandwidth-examples/node_modules/@bandwidth/voice/dist/voice.cjs.development.js:3150:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async file:///home/posu/n2uitive/bandwidth-examples/download-recording.js:17:22
```

### Expected Behavior

The method returns a promise that resolves to audio data.

### Suggested Fix

I didn't study the code enough to know for sure, but I suspect that line 307 of apiController.ts shouldn't be calling callAsJson on the request.

**Comment by ckoegel** [comment]
Thanks for the bug report! @bernardodesousa 
I looked into the SDK and you're definitely right, the `callAsJson` function should not be used for `getDownloadCallRecording`. I've made a PR (#44) to update this and the other getDownload function to use the `callAsText` instead. This will allow you to access the audio data by calling `response.result` in your code. This update will go into our next release of the SDK, which will happen next Tuesday, the 15th. If you need a temporary immediate fix, you can edit line 765 of `@bandwidth\voice\dist\voice.cjs.development.js` to `return req.callAsText(requestOptions);`
